### PR TITLE
Updated to exclude build artifacts

### PR DESCRIPTION
**Pull request by wadewegner**

### CODE REVIEW

**Comment by P3pp3rF1y** [comment]
The gitignore file actually should ignore everything that is not explicitly listed as to be included. Is that not working for you? btw are you on discord? I am P3pp3rF1y#8473 there.

**Comment by wadewegner** [comment]
No, it doesn't work properly. No, not on discord (actually had never heard of it before).

**Comment by P3pp3rF1y** [comment]
In what application does it not exclude these folders for you? It certainly works for me correctly in IntelliJ IDEA and it is the same approach that AE team uses in their gitignore file so I would think it should work in general.

I am also on IRC and Curse, or you can just register on discord, which I find the best as you can access it from anywhere online through web app in addition to it having apps for desktop/mobile.

**Comment by P3pp3rF1y** [comment]
actually you're right that it doesn't ignore this stuff, somehow I got into habbit of using IntelliJ's ignore feature where it didn't ignore this stuff by default. I will however make this into a different change where it will properly ignore the files by default.

**Comment by wadewegner** [comment]
So you're not going to take this pull?

**Comment by P3pp3rF1y** [comment]
No, not this one as my change is different from it. 
Btw, noticed slack bot in your activity stream, Discord is essentially Slack for gamers and most of minecraft community uses that to communicate.

**Comment by P3pp3rF1y** [comment]
and one more btw, I know you have asked before about branches. I generally use a 1.12.x-dev branch for changes and then merge to 1.12.x when I release. that way if I have something in works in dev branch and there's a critical issue I can easily make just a fix for that critical issue in the 1.12.x branch.
Just a kind of habit I got used to at work, doesn't cost much and has saved me a few times already.

**Pull request closed without merging**
