### PR TITLE
Initial API work + Crop farm exceptions

### PR DESCRIPTION
**Pull request by InfinityRaider**
As discussed in #366 

This is a basic framework for an API, with an implementation for custom crops compatibility with the farms.

### CODE REVIEW

**Comment by InfinityRaider** [comment]
Here's a screenshot of my working implementation in AgriCraft:
http://puu.sh/jCuDo/b9a8d6d10b.png

**Comment by GotoLink** [comment]
What is the point of this API.getAPI(version) scheme ?
I understand the package-info is necessary for @API / @Optional.Interface to work at runtime.

Do you intend to implement IAncientWarfareFarmable in a block that doesn't implement IGrowable ?
Because isMature / canFertilize overlap with the other interface...potentially making the implementation redundant on your side.

I made a special case in the meantime 3a8723a

**Comment by InfinityRaider** [comment]
The point of the API scheme was that I was going with a registry type handler first, but I decided that an interface is much more simpler.
You're free to remove it of course, or add in things that you consider would be handy to have access to.

And indeed, my crops implement IGrowable, so I just forward the call to the IGrowable method implementations, however in the future their might be other mods who want compatibility but their plants might not implement IGrowable for some reason.

**Comment by InfinityRaider** [comment]
One little concern about your case for my mod (thanks for that, btw) the harvest method will drop the fruits in the world, I'm not sure if you are okay with that or not.

**Comment by InfinityRaider** [comment]
I've removed the unnecessary API interfaces and you're right, it doesn't make sense to not have IGrowable for plants, so I made it extend IGrowable. If you want I can close this and make a new one to have all the commits lined up nicely.

**Comment by GotoLink** [comment]
The automated farm will pickup every item dropped in the area anyways.
It would be nice to have this squatched indeed.
I don't have any other issue and will soon pull it, so be sure it is ready on your side.

**Comment by InfinityRaider** [comment]
I won't release my next version until you release it from your side.

**Comment by kane-thornwyrd** [comment]
Thank you guys !

**Pull request closed without merging**
