### PR TITLE
Added QuiverBow compatibility

### PR DESCRIPTION
**Pull request by Domochevsky**
This lets the combat NPC use ranged weaponry, as implemented by QuiverBow. :)
(I hope I didn't overlook some spots where NPC attack things.)

http://minecraft.curseforge.com/mc-mods/73811-quiverbow  <- This is the mod in question. Build 78+ will be required.

### CODE REVIEW

**Comment by GotoLink** [comment]
We'd have to decompile your mod to test, is that fine with you ?
In terms of coding style, i would prefer having a separate AI, to avoid the duplicate patch.
Would also be cool not to have to call 6 different methods from that "_WeaponBase" class only to fire an arrow and get a shot delay back. The less method called, the less it would break if you change something on your side.

**Comment by Domochevsky** [comment]
Decompiling is fine, yeah.
You're usually not shooting an arrow, incidentally. Nearly every weapon is using custom projectiles. (Crossbows excluded.)
If you alternatively call onUpdate for items the NPC is holding in general then the whole custom branch for burst fire can be cut out, leaving you with 2 methods that are stable. (one of my other mods is using those as well; QuiverMob.)

**Comment by Domochevsky** [comment]
Changed how QB weaponry is handled, to decrease the points of contact between AW2 and QB. Now burst fire is taken care of via the regular onUpdate, which is a native function.

Oh yeah, additionally I made QuiverBow open source, so you can have a direct gander into that now without any decompilation. :)

**Comment by Domochevsky** [comment]
So... I presume this ain't happening?

**Comment by GotoLink** [comment]
Done.

**Pull request closed without merging**
