### PR TITLE
Allow NPCs to work in Twilight Forest Dimension

### PR DESCRIPTION
**Pull request by DaemonUmbra**
I'm sure changes will be desired, but this will allow NPCs to work in the Twilight Forest dimension (and possibly allow the addition of others)despite the Dim's always night setting, the voting system will allow shims(an interface that will probably get replaced) to oppose each other rather than a straight && vs || fight.

### CODE REVIEW

**Comment by DaemonUmbra** [comment]
I obviously made this at 2AM... I have something to fix

**Comment by P3pp3rF1y** [comment]
Hey, I was looking at this and am not sure what exactly the voting would be used for as I don't see a practical example where it would be needed. Also I would like NPCs to sleep in twilight forest as well, but perhaps define a schedule for them when it's night and when it's day. I will take a look at that.

**Comment by DaemonUmbra** [comment]
I had devised the voting system in case other "shims" are added for other mods that may have funky use of world.isDayTime, and evidently my shim is broken because while time set allows the NPCs to wake up, natural progression of time won't

**Comment by DaemonUmbra** [comment]
I need to do a lot more research into the principles of Minecraft AI before I can do anything like this.

**Pull request closed without merging**
